### PR TITLE
fixed error when retrieving tasks (#2)

### LINKED ISSUE #2: Error when retrieving tasks for a namespace
When expanding a namespace node and the list of tasks is retrieved this error is printed 

java.io.IOException: Process exited with an error: 1 (Exit value: 1) Error: unable to match a printer suitable for the output format "'jsonpath={range .items[*]}{.metadata.name}{\'\\n\'}", allowed formats are: go-template,go-template-file,json,jsonpath,jsonpath-file,name,template,templatefile,yaml

### PR DESCRIPTION
**Pull request by lstocchi**
it fixes #2

### CODE REVIEW

File: src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TasksNode.java [hunk 1]
```diff
@@ -26,7 +26,7 @@ public void load() {
         super.load();
         try {
             NamespaceNode namespaceNode = (NamespaceNode) getParent();
-            ((TektonRootNode)getRoot()).getTkn().getTasks(namespaceNode.toString()).forEach(task -> add(new TaskNode(task)));
+            ((TektonRootNode)getRoot()).getTkn().getTasks(namespaceNode.toString()).forEach(task -> { if(!task.isEmpty()) add(new TaskNode(task)); });
```
Comment (jeffmaury) [inline src/main/java/com/redhat/devtools/intellij/tektoncd/tree/TasksNode.java]: I think this should be done at the CLI level, the result of getTasks should not return empty names !!!. Using Java Streams could filter the list
